# Generated by Django 5.1.2 on 2024-12-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_userpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpoints',
            name='target_word_used',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
