# Generated by Django 5.1.2 on 2024-12-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_userpoints_target_word_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='challenge_started',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='challenge_stopped',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
